spring.datasource.url=jdbc:postgresql://dpg-d71gnb6a2pns73f6vkbg-a:5432/todos_db_69k8
spring.datasource.username=todos_db_69k8_user
spring.datasource.password=BZZbEwBovKABXPijhRNp7ACOOYMfmJ36

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require